# REST Client extention for vscode

### Get Active by date

GET http://localhost:8080/events/?date=2019-11-09 08:57:06 HTTP/1.1

### Get by ID

GET http://localhost:8080/events/1 HTTP/1.1

### Create

POST http://localhost:8080/events HTTP/1.1
content-type: application/json

{
    "Date":"2019-11-11 13:00:05",
    "Duration":5,
    "Description":"сдать домашку"
}

### Remove

GET http://localhost:8080/events/remove/2 HTTP/1.1

### Update

POST http://localhost:8080/events/update/1 HTTP/1.1
content-type: application/json

{
    "Date":"2006-01-02 15:04:11",
    "Duration":5,
    "Description":"сдать домашку"
}