// Code generated by go-swagger; DO NOT EDIT.

package event

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RemoveOKCode is the HTTP code returned for type RemoveOK
const RemoveOKCode int = 200

/*RemoveOK Event removed

swagger:response removeOK
*/
type RemoveOK struct {
}

// NewRemoveOK creates RemoveOK with default headers values
func NewRemoveOK() *RemoveOK {

	return &RemoveOK{}
}

// WriteResponse to the client
func (o *RemoveOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// RemoveBadRequestCode is the HTTP code returned for type RemoveBadRequest
const RemoveBadRequestCode int = 400

/*RemoveBadRequest Bad Request

swagger:response removeBadRequest
*/
type RemoveBadRequest struct {
}

// NewRemoveBadRequest creates RemoveBadRequest with default headers values
func NewRemoveBadRequest() *RemoveBadRequest {

	return &RemoveBadRequest{}
}

// WriteResponse to the client
func (o *RemoveBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// RemoveNotFoundCode is the HTTP code returned for type RemoveNotFound
const RemoveNotFoundCode int = 404

/*RemoveNotFound Event Not Found

swagger:response removeNotFound
*/
type RemoveNotFound struct {
}

// NewRemoveNotFound creates RemoveNotFound with default headers values
func NewRemoveNotFound() *RemoveNotFound {

	return &RemoveNotFound{}
}

// WriteResponse to the client
func (o *RemoveNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
