// Code generated by go-swagger; DO NOT EDIT.

package event

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateOKCode is the HTTP code returned for type UpdateOK
const UpdateOKCode int = 200

/*UpdateOK Event Updated

swagger:response updateOK
*/
type UpdateOK struct {
}

// NewUpdateOK creates UpdateOK with default headers values
func NewUpdateOK() *UpdateOK {

	return &UpdateOK{}
}

// WriteResponse to the client
func (o *UpdateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateBadRequestCode is the HTTP code returned for type UpdateBadRequest
const UpdateBadRequestCode int = 400

/*UpdateBadRequest Bad Request

swagger:response updateBadRequest
*/
type UpdateBadRequest struct {
}

// NewUpdateBadRequest creates UpdateBadRequest with default headers values
func NewUpdateBadRequest() *UpdateBadRequest {

	return &UpdateBadRequest{}
}

// WriteResponse to the client
func (o *UpdateBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateNotFoundCode is the HTTP code returned for type UpdateNotFound
const UpdateNotFoundCode int = 404

/*UpdateNotFound Event Not Found

swagger:response updateNotFound
*/
type UpdateNotFound struct {
}

// NewUpdateNotFound creates UpdateNotFound with default headers values
func NewUpdateNotFound() *UpdateNotFound {

	return &UpdateNotFound{}
}

// WriteResponse to the client
func (o *UpdateNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
