version: '2.0'

services:

  psql:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - ../sql/001_event_table.sql:/docker-entrypoint-initdb.d/001_event_table.sql

  rabbitmq:
    image: 'rabbitmq:3.8'

  api:
    build:
      context: ../.
      dockerfile: ./docker/api/Dockerfile
    image: calendar_api
    command: --connection="host=psql user=myuser password=mypass dbname=mydb"
    depends_on: 
      - psql
    restart: always
    ports:
      - 8080:8080

  scheduler:
    build:
      context: ../.
      dockerfile: ./docker/scheduler/Dockerfile
    image: calendar_scheduler
    command: --connection="host=psql user=myuser password=mypass dbname=mydb" --amqpurl=amqp://rabbitmq?connection_attempts=5&retry_delay=5
    depends_on: 
      - psql
      - rabbitmq
    restart: always
