// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calendar.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Event) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Event) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Events struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Events) Reset()         { *m = Events{} }
func (m *Events) String() string { return proto.CompactTextString(m) }
func (*Events) ProtoMessage()    {}
func (*Events) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{1}
}

func (m *Events) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Events.Unmarshal(m, b)
}
func (m *Events) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Events.Marshal(b, m, deterministic)
}
func (m *Events) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Events.Merge(m, src)
}
func (m *Events) XXX_Size() int {
	return xxx_messageInfo_Events.Size(m)
}
func (m *Events) XXX_DiscardUnknown() {
	xxx_messageInfo_Events.DiscardUnknown(m)
}

var xxx_messageInfo_Events proto.InternalMessageInfo

func (m *Events) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type ID struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{2}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Succesfull struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Succesfull) Reset()         { *m = Succesfull{} }
func (m *Succesfull) String() string { return proto.CompactTextString(m) }
func (*Succesfull) ProtoMessage()    {}
func (*Succesfull) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{3}
}

func (m *Succesfull) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Succesfull.Unmarshal(m, b)
}
func (m *Succesfull) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Succesfull.Marshal(b, m, deterministic)
}
func (m *Succesfull) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Succesfull.Merge(m, src)
}
func (m *Succesfull) XXX_Size() int {
	return xxx_messageInfo_Succesfull.Size(m)
}
func (m *Succesfull) XXX_DiscardUnknown() {
	xxx_messageInfo_Succesfull.DiscardUnknown(m)
}

var xxx_messageInfo_Succesfull proto.InternalMessageInfo

func (m *Succesfull) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type GetResponse struct {
	// Types that are valid to be assigned to Result:
	//	*GetResponse_Event
	//	*GetResponse_Error
	Result               isGetResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{4}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

type isGetResponse_Result interface {
	isGetResponse_Result()
}

type GetResponse_Event struct {
	Event *Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type GetResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetResponse_Event) isGetResponse_Result() {}

func (*GetResponse_Error) isGetResponse_Result() {}

func (m *GetResponse) GetResult() isGetResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetResponse) GetEvent() *Event {
	if x, ok := m.GetResult().(*GetResponse_Event); ok {
		return x.Event
	}
	return nil
}

func (m *GetResponse) GetError() string {
	if x, ok := m.GetResult().(*GetResponse_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetResponse_Event)(nil),
		(*GetResponse_Error)(nil),
	}
}

type ChangeResponse struct {
	// Types that are valid to be assigned to Result:
	//	*ChangeResponse_Ok
	//	*ChangeResponse_Error
	Result               isChangeResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ChangeResponse) Reset()         { *m = ChangeResponse{} }
func (m *ChangeResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeResponse) ProtoMessage()    {}
func (*ChangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{5}
}

func (m *ChangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeResponse.Unmarshal(m, b)
}
func (m *ChangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeResponse.Marshal(b, m, deterministic)
}
func (m *ChangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeResponse.Merge(m, src)
}
func (m *ChangeResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeResponse.Size(m)
}
func (m *ChangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeResponse proto.InternalMessageInfo

type isChangeResponse_Result interface {
	isChangeResponse_Result()
}

type ChangeResponse_Ok struct {
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3,oneof"`
}

type ChangeResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ChangeResponse_Ok) isChangeResponse_Result() {}

func (*ChangeResponse_Error) isChangeResponse_Result() {}

func (m *ChangeResponse) GetResult() isChangeResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ChangeResponse) GetOk() bool {
	if x, ok := m.GetResult().(*ChangeResponse_Ok); ok {
		return x.Ok
	}
	return false
}

func (m *ChangeResponse) GetError() string {
	if x, ok := m.GetResult().(*ChangeResponse_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ChangeResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ChangeResponse_Ok)(nil),
		(*ChangeResponse_Error)(nil),
	}
}

func init() {
	proto.RegisterType((*Event)(nil), "Event")
	proto.RegisterType((*Events)(nil), "Events")
	proto.RegisterType((*ID)(nil), "ID")
	proto.RegisterType((*Succesfull)(nil), "Succesfull")
	proto.RegisterType((*GetResponse)(nil), "GetResponse")
	proto.RegisterType((*ChangeResponse)(nil), "ChangeResponse")
}

func init() { proto.RegisterFile("calendar.proto", fileDescriptor_e3d25d49f056cdb2) }

var fileDescriptor_e3d25d49f056cdb2 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xd1, 0x8e, 0x93, 0x40,
	0x14, 0x2d, 0xd0, 0x8e, 0xf4, 0x62, 0xaa, 0x99, 0x18, 0x83, 0xc4, 0x54, 0xe4, 0x89, 0xa7, 0xa9,
	0xa9, 0xf1, 0x03, 0x6c, 0x31, 0x6d, 0x9f, 0x4c, 0x46, 0x7d, 0xf1, 0x8d, 0xc2, 0x2d, 0x92, 0x52,
	0x86, 0x0c, 0x43, 0xbf, 0xc7, 0x7f, 0xd8, 0x1f, 0xdc, 0x30, 0xd0, 0x6e, 0x97, 0x4d, 0x76, 0x9f,
	0x60, 0xee, 0x39, 0xf7, 0x9c, 0x73, 0xef, 0x85, 0x59, 0x12, 0x17, 0x58, 0xa6, 0xb1, 0x64, 0x95,
	0x14, 0x4a, 0x78, 0x9f, 0x32, 0x21, 0xb2, 0x02, 0x17, 0xfa, 0xb5, 0x6f, 0x0e, 0x0b, 0x95, 0x9f,
	0xb0, 0x56, 0xf1, 0xa9, 0xea, 0x09, 0xf3, 0x21, 0x21, 0x6d, 0x64, 0xac, 0x72, 0x51, 0x76, 0x78,
	0xf0, 0xdf, 0x80, 0xc9, 0x8f, 0x33, 0x96, 0x8a, 0xce, 0xc0, 0xcc, 0x53, 0xd7, 0xf0, 0x8d, 0xd0,
	0xe2, 0x66, 0x9e, 0x52, 0x06, 0xe3, 0x34, 0x56, 0xe8, 0x9a, 0xbe, 0x11, 0x3a, 0x4b, 0x8f, 0x75,
	0x42, 0xec, 0x22, 0xc4, 0x7e, 0x5f, 0x9c, 0xb8, 0xe6, 0xd1, 0x6f, 0x60, 0x5f, 0xb4, 0x5d, 0x4b,
	0xf7, 0x7c, 0x78, 0xd2, 0x13, 0xf5, 0x04, 0x7e, 0xa5, 0x52, 0x1f, 0x9c, 0x14, 0xeb, 0x44, 0xe6,
	0x95, 0xee, 0x1c, 0xfb, 0x46, 0x38, 0xe5, 0xb7, 0xa5, 0x20, 0x04, 0xa2, 0x13, 0xd6, 0x74, 0x0e,
	0x04, 0xf5, 0x9f, 0x6b, 0xf8, 0x56, 0xe8, 0x2c, 0x09, 0xd3, 0x00, 0xef, 0xab, 0xc1, 0x3b, 0x30,
	0x77, 0xd1, 0x70, 0x90, 0xe0, 0x23, 0xc0, 0xaf, 0x26, 0x49, 0xb0, 0x3e, 0x34, 0x45, 0xd1, 0xa2,
	0xe2, 0xa8, 0x51, 0x9b, 0x9b, 0xe2, 0x18, 0xfc, 0x04, 0x67, 0x83, 0x8a, 0x63, 0x5d, 0x89, 0xb2,
	0x46, 0x3a, 0x87, 0x89, 0x16, 0xd3, 0x8c, 0xab, 0xc3, 0x76, 0xc4, 0xbb, 0x32, 0x7d, 0x0f, 0x13,
	0x94, 0x52, 0x48, 0xbd, 0x96, 0xa9, 0xae, 0xb7, 0xcf, 0x95, 0x0d, 0x44, 0x62, 0xdd, 0x14, 0x2a,
	0x88, 0x60, 0xb6, 0xfe, 0x17, 0x97, 0x19, 0x5e, 0x35, 0xdf, 0x3e, 0x58, 0x6e, 0x47, 0xad, 0xe9,
	0xcb, 0x2a, 0xcb, 0x3b, 0x03, 0xec, 0x75, 0x7f, 0x6b, 0xea, 0x02, 0x59, 0x4b, 0x6c, 0x97, 0xdc,
	0xe7, 0xf1, 0xfa, 0x2f, 0xfd, 0x02, 0xd3, 0x0d, 0xaa, 0xef, 0x89, 0xca, 0xcf, 0x48, 0x9f, 0xb9,
	0x91, 0xf7, 0x8a, 0xf5, 0x3b, 0x74, 0xc1, 0xda, 0xa0, 0xa2, 0x16, 0xdb, 0x45, 0xde, 0x6b, 0xf6,
	0x78, 0x74, 0xc2, 0xf1, 0x24, 0xce, 0xd8, 0x81, 0x6f, 0xd8, 0x60, 0x8c, 0xcf, 0x40, 0xfe, 0x54,
	0xe9, 0x6d, 0x8a, 0x21, 0x65, 0x45, 0xfe, 0x8e, 0x33, 0x59, 0x25, 0x7b, 0xa2, 0x13, 0x7c, 0xbd,
	0x0f, 0x00, 0x00, 0xff, 0xff, 0x17, 0x57, 0x3a, 0x42, 0xaf, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalendarClient is the client API for Calendar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalendarClient interface {
	Create(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error)
	GetActive(ctx context.Context, in *timestamp.Timestamp, opts ...grpc.CallOption) (*Events, error)
	Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*GetResponse, error)
	Remove(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ChangeResponse, error)
	Update(ctx context.Context, in *Event, opts ...grpc.CallOption) (*ChangeResponse, error)
}

type calendarClient struct {
	cc *grpc.ClientConn
}

func NewCalendarClient(cc *grpc.ClientConn) CalendarClient {
	return &calendarClient{cc}
}

func (c *calendarClient) Create(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/Calendar/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) GetActive(ctx context.Context, in *timestamp.Timestamp, opts ...grpc.CallOption) (*Events, error) {
	out := new(Events)
	err := c.cc.Invoke(ctx, "/Calendar/GetActive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/Calendar/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) Remove(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ChangeResponse, error) {
	out := new(ChangeResponse)
	err := c.cc.Invoke(ctx, "/Calendar/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) Update(ctx context.Context, in *Event, opts ...grpc.CallOption) (*ChangeResponse, error) {
	out := new(ChangeResponse)
	err := c.cc.Invoke(ctx, "/Calendar/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalendarServer is the server API for Calendar service.
type CalendarServer interface {
	Create(context.Context, *Event) (*Event, error)
	GetActive(context.Context, *timestamp.Timestamp) (*Events, error)
	Get(context.Context, *ID) (*GetResponse, error)
	Remove(context.Context, *ID) (*ChangeResponse, error)
	Update(context.Context, *Event) (*ChangeResponse, error)
}

// UnimplementedCalendarServer can be embedded to have forward compatible implementations.
type UnimplementedCalendarServer struct {
}

func (*UnimplementedCalendarServer) Create(ctx context.Context, req *Event) (*Event, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedCalendarServer) GetActive(ctx context.Context, req *timestamp.Timestamp) (*Events, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActive not implemented")
}
func (*UnimplementedCalendarServer) Get(ctx context.Context, req *ID) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedCalendarServer) Remove(ctx context.Context, req *ID) (*ChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (*UnimplementedCalendarServer) Update(ctx context.Context, req *Event) (*ChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterCalendarServer(s *grpc.Server, srv CalendarServer) {
	s.RegisterService(&_Calendar_serviceDesc, srv)
}

func _Calendar_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).Create(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_GetActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(timestamp.Timestamp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).GetActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/GetActive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).GetActive(ctx, req.(*timestamp.Timestamp))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).Get(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).Remove(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).Update(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calendar_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Calendar",
	HandlerType: (*CalendarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Calendar_Create_Handler,
		},
		{
			MethodName: "GetActive",
			Handler:    _Calendar_GetActive_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Calendar_Get_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Calendar_Remove_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Calendar_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calendar.proto",
}
