# swagger validate ./web/swagger.yml
swagger: '2.0'
info:
  version: '1.0.0'
  title: Calendar
schemes: [http]
basePath: /
consumes: [application/json]
produces: [application/json]
paths:
  /events:
    post:
      tags: [event]
      operationId: Create
      parameters:
      - in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/Event'
      responses:
        201:
          description: Event Created
          schema:
            $ref: '#/definitions/Event'
        400:
          description: Bad Request
    get:
      tags: [event]
      operationId: List
      parameters:
      - in: query
        name: date
        type: string
      responses:
        200:
          description: 'Active event list by date'
          schema:
            type: array
            items:
                $ref: '#/definitions/Event'
  /events/{eventID}:
    get:
      tags: [event]
      operationId: Get
      parameters:
      - name: eventID
        in: path
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Event get
          schema:
            $ref: '#/definitions/Event'
        400:
          description: Bad Request
        404:
          description: Event Not Found
  # /events/remove/{eventID}:
  #   get:
  #     tags: [event]
  #     operationId: Remove
  #     parameters:
  #     - name: eventID
  #       in: path
  #       required: true
  #       type: integer
  #       format: int64
  #     responses:
  #       200:
  #         description: Event removed
  #       400:
  #         description: Bad Request
  #       404:
  #         description: Event Not Found

definitions:
  Event:
    type: object
    required:
    - date
    - duration
    - description
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      date:
        type: string
        example: 2019-09-07 08:20:00
      duration:
        type: integer
        format: int64
        example: 5 #Seconds
      description:
        type: string
        example: сдать домашку
